# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eme < Formula
  desc "Mission control for your AI coding agents — run each in its own git worktree + tmux session"
  homepage "https://eme.jinmu.me"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JinmuGo/eme/releases/download/v0.1.0/eme_Darwin_x86_64.tar.gz"
      sha256 "5607b5ea053bad9963dc3c46e50004da03e9a186e2f7f7a3861d2e48c6b9e996"

      define_method(:install) do
        bin.install "eme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JinmuGo/eme/releases/download/v0.1.0/eme_Darwin_arm64.tar.gz"
      sha256 "7a6d18863ebcadba737530304f3d4cd544f4c1c47130b9a9a554790a10c12fa7"

      define_method(:install) do
        bin.install "eme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JinmuGo/eme/releases/download/v0.1.0/eme_Linux_x86_64.tar.gz"
      sha256 "3470f74a2e5d3c2010189871bd3dcdcee1ffd5d5abfdbcf19c19e3603dee0b8f"
      define_method(:install) do
        bin.install "eme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JinmuGo/eme/releases/download/v0.1.0/eme_Linux_arm64.tar.gz"
      sha256 "6b1090bc02f6440e492c354d397c5162a424f88bc7a91e2f249bc75e78979ceb"
      define_method(:install) do
        bin.install "eme"
      end
    end
  end

  test do
    system "#{bin}/eme", "--version"
  end
end
